services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - shion_pro_grafana_storage:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    restart: always
    volumes:
      - shion_pro_grafana_storage:/var/lib/grafana
      - ./oauth_secret:/oauth_secret
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - "GF_AUTH_GITHUB_CLIENT_SECRET__FILE=/oauth_secret"
    ports:
      - "3091:3000"
volumes:
  shion_pro_grafana_storage: {}
  shion_pro_prometheus_storage: {}
